#Recuperar todas las peliculas 
##GET http://localhost:3000/movies

###Recuperar todas las materias
GET http://localhost:64000/materias

###Recuperar materia por ID

GET http://localhost:64000/materias/A

###Crear una materia

POST http://localhost:64000/materias
Content-Type: application/json 

{
  "name": "Logica",
  "acronimo": "LOG"
}
 

### Borrar una materia 
DELETE http://localhost:64000/Materias/A

### Modificar parcialmente una materia 
PATCH http://localhost:64000/materias/A
Content-Type: : application/json


{
    "name": "Logica discreta",
    "acronimo": "LOS"
}

###
GET http://localhost:64000/matXcorre/05b2f6d8-85b1-4a79-ba15-62ca8786442a